{
  "input": {
    "message": "2019/08/25 23:59:53 [error] 9841#9841: *103137592 connect() failed (111: Connection refused) while connecting to upstream, client: 51.255.128.104, server: api.prod.sekoia.io, request: \"GET /v1/apiauth/auth/health HTTP/1.1\", upstream: \"http://10.110.30.121:80/v1/apiauth/auth/health\", host: \"api.sekoia.io\""
  },
  "expected": {
    "message": "2019/08/25 23:59:53 [error] 9841#9841: *103137592 connect() failed (111: Connection refused) while connecting to upstream, client: 51.255.128.104, server: api.prod.sekoia.io, request: \"GET /v1/apiauth/auth/health HTTP/1.1\", upstream: \"http://10.110.30.121:80/v1/apiauth/auth/health\", host: \"api.sekoia.io\"",
    "event": {
      "category": [
        "web"
      ],
      "dataset": "access",
      "type": [
        "error"
      ]
    },
    "@timestamp": "2019-08-25T23:59:53Z",
    "destination": {
      "address": "api.prod.sekoia.io",
      "domain": "api.prod.sekoia.io"
    },
    "error": {
      "message": "connect() failed (111: Connection refused) while connecting to upstream"
    },
    "host": {
      "name": "api.sekoia.io"
    },
    "http": {
      "request": {
        "method": "GET"
      },
      "version": "1.1"
    },
    "log": {
      "level": "error"
    },
    "observer": {
      "product": "nginx",
      "type": "WEB server",
      "vendor": "F5"
    },
    "related": {
      "hosts": [
        "10.110.30.121",
        "api.prod.sekoia.io"
      ],
      "ip": [
        "51.255.128.104"
      ]
    },
    "source": {
      "address": "51.255.128.104",
      "ip": "51.255.128.104"
    },
    "url": {
      "domain": "10.110.30.121",
      "original": "/v1/apiauth/auth/health",
      "path": "/v1/apiauth/auth/health",
      "port": 80
    }
  }
}